/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Cube(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./models/cubing.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(()=>{
    actions?.jumping?.play();
  })
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="Cube"
          castShadow
          receiveShadow
          geometry={nodes.Cube.geometry}
          material={materials.Material}
          position={[-0.008, 0.047, -0.023]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('./models/cubing.glb')
